### ISSUE TITLE
Release to melodic

### ISSUE THREAD

**Issue by christian-rauch** [ipab-slmc/pybind11_catkin#4]
Could we release this to ROS `melodic`?

**Comment by wxmerkt** [comment]
I'd love to and spend quite a bunch of time on it - but it was blocked upstream, see the long discussion here:

https://github.com/ros/rosdistro/pull/18473

I'd love to try again. We are fully namespacing things so that it does not create any conflicts and there are users outside of our group. The only conflict that can occur is if a user includes _both_ ``pybind11`` and ``pybind11_catkin`` - which should not happen.

**Comment by wxmerkt** [comment]
PR opened and pending: https://github.com/ros/rosdistro/pull/19866

**Comment by wxmerkt** [comment]
The package has now been released for melodic and will be available after the next sync.
